opentmf:
  client-type: jdk
  http-clients:
    firstBasic:
      client-type: netty
      fixed-headers:
        header1: value1
      basic-auth:
        username: user1
        password: pass1

    secondBasic:
      client-type: netty
      fixed-headers:
        header1: value1
        header2: value2
      basic-auth:
        username: user2
        password: pass2

    firstBearer:
      client-type: netty
      fixed-headers:
        header1: value1
      bearer-auth:
        use-mock: false
        token-url: http://localhost:1080/token
        client-id: user
        client-secret: pass
        username-field: username
        form-data:
          username: user
          password: pass
          scope: openid
          grant_type: password

    healthCheck:
      client-type: netty
      request-timeout: 5s
      response-timeout: 10s

    syncBasic:
      client-type: jdk
      basic-auth:
        username: syncUser
        password: syncPass

    syncBearer:
      client-type: jdk
      bearer-auth:
        use-mock: true
        token-url: http://localhost:1080/token
        client-id: user
        client-secret: pass
        form-data:
          grant_type: client_credentials
          scope: openid

    stormSync:
      client-type: jdk
      resilience:
        enabled: true
        circuit-breaker:
          sliding-window-size: 4
          minimum-number-of-calls: 4
          wait-duration-in-open-state: 60s
        bulkhead:
          max-concurrent-calls: 10

    stormReactive:
      client-type: netty
      resilience:
        enabled: true
        circuit-breaker:
          sliding-window-size: 4
          minimum-number-of-calls: 4
          wait-duration-in-open-state: 60s

    apacheRetry:
      client-type: apache

    syncRetryAfter:
      client-type: jdk
      max-retry-after: 2s

    reactiveRetryAfter:
      client-type: netty
      max-retry-after: 2s
