<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.opentmf.client</groupId>
    <artifactId>opentmf-http-clients</artifactId>
    <version>2.1.5-SNAPSHOT</version>
  </parent>

  <artifactId>opentmf-http-clients-common</artifactId>
  <name>opentmf-http-clients-common</name>

  <description>
    Common models, interfaces, and utilities for OpenTMF HTTP clients.
  </description>

  <dependencies>
    <dependency>
      <groupId>org.opentmf.commons</groupId>
      <artifactId>opentmf-commons</artifactId>
      <version>${opentmf-commons.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
    </dependency>
    <dependency>
      <groupId>jakarta.validation</groupId>
      <artifactId>jakarta.validation-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>

    <!-- Optional resilience4j decoration -->
    <dependency>
      <groupId>io.github.resilience4j</groupId>
      <artifactId>resilience4j-circuitbreaker</artifactId>
      <version>${resilience4j.version}</version>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>io.github.resilience4j</groupId>
      <artifactId>resilience4j-bulkhead</artifactId>
      <version>${resilience4j.version}</version>
      <optional>true</optional>
    </dependency>
  </dependencies>

</project>
